apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
  namespace: platform
spec:
  type: NodePort
  selector:
    app: dotnet-service
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30050