apiVersion: v1
kind: Service
metadata:
  name: java-service
  namespace: platform
spec:
  type: NodePort
  selector:
    app: java-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
