apiVersion: v1
kind: Service
metadata:
  name: platform-api
  namespace: platform
spec:
  type: NodePort
  selector:
    app: platform-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
